groups:
  - name: application_alerts
    rules:
      - alert: HighRequestLatency
        expr: http_request_duration_seconds > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High request latency on {{ $labels.instance }}
          description: Request latency is above 2s (current value: {{ $value }}s)

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate is above 10% in the last 5 minutes

      - alert: LowStockLevel
        expr: product_stock_level < 10
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Low stock level for product {{ $labels.product_id }}
          description: Stock level is below 10 units

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage on {{ $labels.instance }}
          description: Memory usage is above 90%

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage on {{ $labels.instance }}
          description: CPU usage is above 80%

      - alert: DatabaseConnectionPoolSaturation
        expr: rate(db_query_duration_seconds_count[5m]) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Database connection pool near saturation
          description: High number of database queries detected

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Redis high memory usage
          description: Redis memory usage is above 80%
